import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        // Zenthea Brand Colors - All reference CSS variables
        zenthea: {
          teal: 'var(--zenthea-teal)',
          purple: 'var(--zenthea-purple)',
          coral: 'var(--zenthea-coral)',
          cream: 'var(--zenthea-cream)',
          primary: 'var(--color-interactive-primary)',
          secondary: 'var(--color-interactive-secondary)',
          accent: 'var(--color-interactive-primary)',
          background: 'var(--color-background-primary)',
          // Brand color variations
          'teal-50': 'var(--zenthea-teal-50)',
          'teal-100': 'var(--zenthea-teal-100)',
          'teal-200': 'var(--zenthea-teal-200)',
          'teal-300': 'var(--zenthea-teal-300)',
          'teal-400': 'var(--zenthea-teal-400)',
          'teal-500': 'var(--zenthea-teal-500)',
          'teal-600': 'var(--zenthea-teal-600)',
          'teal-700': 'var(--zenthea-teal-700)',
          'teal-800': 'var(--zenthea-teal-800)',
          'teal-900': 'var(--zenthea-teal-900)',
          'teal-950': 'var(--zenthea-teal-950)',
          'purple-50': 'var(--zenthea-purple-50)',
          'purple-100': 'var(--zenthea-purple-100)',
          'purple-200': 'var(--zenthea-purple-200)',
          'purple-300': 'var(--zenthea-purple-300)',
          'purple-400': 'var(--zenthea-purple-400)',
          'purple-500': 'var(--zenthea-purple-500)',
          'purple-600': 'var(--zenthea-purple-600)',
          'purple-700': 'var(--zenthea-purple-700)',
          'purple-800': 'var(--zenthea-purple-800)',
          'purple-900': 'var(--zenthea-purple-900)',
          'purple-950': 'var(--zenthea-purple-950)',
          'coral-50': 'var(--zenthea-coral-50)',
          'coral-100': 'var(--zenthea-coral-100)',
          'coral-200': 'var(--zenthea-coral-200)',
          'coral-300': 'var(--zenthea-coral-300)',
          'coral-400': 'var(--zenthea-coral-400)',
          'coral-500': 'var(--zenthea-coral-500)',
          'coral-600': 'var(--zenthea-coral-600)',
          'coral-700': 'var(--zenthea-coral-700)',
          'coral-800': 'var(--zenthea-coral-800)',
          'coral-900': 'var(--zenthea-coral-900)',
          'coral-950': 'var(--zenthea-coral-950)',
          'cream-50': 'var(--zenthea-cream-50)',
          'cream-100': 'var(--zenthea-cream-100)',
          'cream-200': 'var(--zenthea-cream-200)',
          'cream-300': 'var(--zenthea-cream-300)',
          'cream-400': 'var(--zenthea-cream-400)',
          'cream-500': 'var(--zenthea-cream-500)',
          'cream-600': 'var(--zenthea-cream-600)',
          'cream-700': 'var(--zenthea-cream-700)',
          'cream-800': 'var(--zenthea-cream-800)',
          'cream-900': 'var(--zenthea-cream-900)',
          'cream-950': 'var(--zenthea-cream-950)',
        },
        // Semantic Colors - All reference CSS variables
        background: {
          DEFAULT: 'hsl(var(--background))',
          primary: 'var(--color-background-primary)',
          secondary: 'var(--color-background-secondary)',
          tertiary: 'var(--color-background-tertiary)',
          elevated: 'var(--color-background-elevated)',
          overlay: 'var(--color-background-overlay)',
        },
        surface: {
          primary: 'var(--color-surface-primary)',
          secondary: 'var(--color-surface-secondary)',
          tertiary: 'var(--color-surface-tertiary)',
          elevated: 'var(--color-surface-elevated)',
          interactive: 'var(--color-surface-interactive)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          disabled: 'var(--color-text-disabled)',
          inverse: 'var(--color-text-inverse)',
          link: 'var(--color-text-link)',
          'link-hover': 'var(--color-text-link-hover)',
        },
        border: {
          DEFAULT: 'hsl(var(--border))',
          primary: 'var(--color-border-primary)',
          secondary: 'var(--color-border-secondary)',
          tertiary: 'var(--color-border-tertiary)',
          focus: 'var(--color-border-focus)',
          error: 'var(--color-border-error)',
          success: 'var(--color-border-success)',
          warning: 'var(--color-border-warning)',
        },
        interactive: {
          primary: 'var(--color-interactive-primary)',
          'primary-hover': 'var(--color-interactive-primary-hover)',
          'primary-active': 'var(--color-interactive-primary-active)',
          secondary: 'var(--color-interactive-secondary)',
          'secondary-hover': 'var(--color-interactive-secondary-hover)',
          'secondary-active': 'var(--color-interactive-secondary-active)',
          disabled: 'var(--color-interactive-disabled)',
        },
        // Healthcare Colors - All reference CSS variables
        healthcare: {
          patient: 'var(--healthcare-patient)',
          'patient-active': 'var(--healthcare-patient-active)',
          'patient-inactive': 'var(--healthcare-patient-inactive)',
          'patient-discharged': 'var(--healthcare-patient-discharged)',
          appointment: 'var(--healthcare-appointment)',
          'appointment-scheduled': 'var(--healthcare-appointment-scheduled)',
          'appointment-confirmed': 'var(--healthcare-appointment-confirmed)',
          'appointment-cancelled': 'var(--healthcare-appointment-cancelled)',
          'appointment-rescheduled': 'var(--healthcare-appointment-rescheduled)',
          vital: 'var(--healthcare-vital)',
          'vital-normal': 'var(--healthcare-vital-normal)',
          'vital-elevated': 'var(--healthcare-vital-elevated)',
          'vital-critical': 'var(--healthcare-vital-critical)',
          'vital-low': 'var(--healthcare-vital-low)',
          lab: {
            normal: 'var(--healthcare-lab-normal)',
            abnormal: 'var(--healthcare-lab-abnormal)',
            critical: 'var(--healthcare-lab-critical)',
            pending: 'var(--healthcare-lab-pending)',
            unavailable: 'var(--healthcare-lab-unavailable)',
          },
          alert: {
            info: 'var(--healthcare-alert-info)',
            warning: 'var(--healthcare-alert-warning)',
            error: 'var(--healthcare-alert-error)',
            critical: 'var(--healthcare-alert-critical)',
            success: 'var(--healthcare-alert-success)',
          },
          treatment: {
            active: 'var(--healthcare-treatment-active)',
            completed: 'var(--healthcare-treatment-completed)',
            pending: 'var(--healthcare-treatment-pending)',
            cancelled: 'var(--healthcare-treatment-cancelled)',
          },
          insurance: {
            active: 'var(--healthcare-insurance-active)',
            pending: 'var(--healthcare-insurance-pending)',
            denied: 'var(--healthcare-insurance-denied)',
            expired: 'var(--healthcare-insurance-expired)',
          },
          medical: 'var(--healthcare-medical)',
          normal: 'var(--healthcare-normal)',
          abnormal: 'var(--healthcare-abnormal)',
          critical: 'var(--healthcare-critical)',
          stable: 'var(--healthcare-stable)',
          unstable: 'var(--healthcare-unstable)',
          messaging: 'var(--healthcare-alert-info)',
          profile: 'var(--healthcare-patient)',
          security: 'var(--healthcare-alert-warning)',
        },
        // Status Colors - All reference CSS variables
        status: {
          success: 'var(--color-status-success)',
          warning: 'var(--color-status-warning)',
          error: 'var(--color-status-error)',
          info: 'var(--color-status-info)',
          critical: 'var(--color-status-critical)',
          'success-bg': 'var(--color-status-success-bg)',
          'warning-bg': 'var(--color-status-warning-bg)',
          'error-bg': 'var(--color-status-error-bg)',
          'info-bg': 'var(--color-status-info-bg)',
          'critical-bg': 'var(--color-status-critical-bg)',
        },
        // Legacy shadcn/ui colors - All reference CSS variables
        bg: 'hsl(var(--background))',
        fg: 'hsl(var(--foreground))',
        muted: 'hsl(var(--muted))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        foreground: 'hsl(var(--foreground))',
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        DEFAULT: 'var(--radius)',
      },
      boxShadow: {
        '1': 'var(--shadow-1)',
        '2': 'var(--shadow-2)',
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('@tailwindcss/typography'),
  ],
}

export default config
